apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend
  namespace: dataspace-dev
  labels:
    app: frontend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: frontend
  template:
    metadata:
      labels:
        app: frontend
    spec:
      imagePullSecrets:
        - name: ghcr-secret
      containers:
        - name: frontend
          image: ghcr.io/dev-epireum-com/dataspace:b7ecf6-frontend
          imagePullPolicy: Always
          ports:
            - containerPort: 3000
          env:
            - name: VITE_API_URL
              value: "http://localhost:8000"
          resources:
            requests:
              cpu: "100m"
              memory: "128Mi"
            limits:
              cpu: "500m"
              memory: "256Mi"
